language: php
sudo: required
php:
 - '7.0'
 - '7.1'

services:
 - mysql

before_script:
 - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp bin/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
 - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then sudo cp bin/www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
 - composer self-update
 - chmod ugo+x bin/travis.sh
 - ./bin/travis.sh $(phpenv version-name) $(pwd)

before_install:
 - mysql -e 'SET NAMES utf8; create database IF NOT EXISTS wordpress;'

install:
 - travis_retry composer install --no-interaction --prefer-source --dev

notifications:
 on_success: never
 on_failure: always