language: php
php:
 - '5.5'
 - '5.6'
 - '7.0'
 - hhvm

before_script:
   - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --dev

notifications:
  on_success: never
  on_failure: always