dist: bionic
language: php

env:
 global:
  - SETUP=stable

jobs:
 fast_finish: true
 include:
  - php: 7.2

cache:
 directories:
  - $HOME/.composer/cache

services:
 - redis
 - mysql

before_install:
 - phpenv config-rm xdebug.ini || true
 - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - printf "\n" | pecl install -f redis
 - travis_retry composer self-update
 - mysql -e 'SET NAMES utf8; create database IF NOT EXISTS wordpress;'
 - mysql -e 'SET NAMES utf8; create database IF NOT EXISTS tr_v51_alt;'
 - mysql -e 'USE tr_v51_alt; CREATE TABLE IF NOT EXISTS some_table ( id int, text_field varchar(255) );'
 - chmod ugo+x bin/travis.sh
 - ./bin/travis.sh $(phpenv version-name) $(pwd)

install:
 - travis_retry composer install --no-interaction --prefer-source

script:
 - vendor/bin/phpunit