language: php
sudo: required
php:
 - '7.0'

services:
 - mysql

before_script:
 - composer self-update
 - chmod ugo+x bin/travis.sh
 - ./bin/travis.sh $(phpenv version-name) $(pwd)

before_install:
 - mysql -e 'SET NAMES utf8; create database IF NOT EXISTS wordpress;'

install:
 - travis_retry composer install --no-interaction --prefer-source --dev

notifications:
 on_success: never
 on_failure: always